import type { ChallengeRegistry, ChallengeLevel } from './types';

export const challengeRegistry: ChallengeRegistry = {
  beginner: [
    {
      id: 'beginner-01-login-form',
      title: 'Login Form',
      description:
        'Test a login form with email/password validation, error states, and success redirect',
      level: 'beginner',
      category: 'Forms',
      objectives: [
        'Locate and interact with form inputs',
        'Test form validation (required fields, email format)',
        'Verify error messages are displayed',
        'Test successful login flow',
        'Assert navigation after successful login',
      ],
      hints: [
        'Use page.getByLabel() to find form inputs',
        'Use page.getByRole("button", { name: "Login" }) to find the submit button',
        'Wait for error messages with page.getByText()',
        'Use page.waitForURL() to verify navigation',
      ],
      componentPath: './beginner/LoginForm',
      apiEndpoints: ['/api/auth/login'],
      estimatedTime: 15,
      order: 1,
    },
    {
      id: 'beginner-02-product-list',
      title: 'Product List',
      description: 'Test a product listing page with search, filters, and pagination',
      level: 'beginner',
      category: 'Lists',
      objectives: [
        'Verify all products are loaded and displayed',
        'Test search functionality',
        'Test category filters',
        'Navigate through pagination',
        'Assert product details are correct',
      ],
      hints: [
        'Use page.locator() with data-testid attributes',
        'Count items with .count()',
        'Test filters by clicking and verifying results',
        'Use page.getByRole("button", { name: "Next" }) for pagination',
      ],
      componentPath: './beginner/ProductList',
      apiEndpoints: ['/api/items'],
      estimatedTime: 20,
      order: 2,
    },
    {
      id: 'beginner-03-shopping-cart',
      title: 'Shopping Cart',
      description: 'Test adding/removing items from cart and quantity updates',
      level: 'beginner',
      category: 'State Management',
      objectives: [
        'Add products to cart',
        'Update product quantities',
        'Remove products from cart',
        'Verify cart total calculations',
        'Test empty cart state',
      ],
      hints: [
        'Use page.getByRole("button", { name: /add to cart/i })',
        'Find quantity inputs with page.getByRole("spinbutton")',
        'Assert text content with expect(locator).toHaveText()',
        'Test cart badge updates',
      ],
      componentPath: './beginner/ShoppingCart',
      estimatedTime: 25,
      order: 3,
    },
    {
      id: 'beginner-04-user-profile',
      title: 'User Profile',
      description: 'Test viewing and editing user profile information',
      level: 'beginner',
      category: 'Forms',
      objectives: [
        'Load and display user information',
        'Enable edit mode',
        'Update profile fields',
        'Validate required fields',
        'Save changes and verify updates',
      ],
      hints: [
        'Use page.getByRole("button", { name: "Edit" })',
        'Fill inputs with .fill()',
        'Use .clear() before filling new values',
        'Wait for success messages',
      ],
      componentPath: './beginner/UserProfile',
      apiEndpoints: ['/api/auth/me', '/api/users/:id'],
      estimatedTime: 20,
      order: 4,
    },
    {
      id: 'beginner-05-search-bar',
      title: 'Search Bar',
      description: 'Test search functionality with debouncing and live results',
      level: 'beginner',
      category: 'Input',
      objectives: [
        'Type in search input',
        'Wait for debounced search',
        'Verify search results appear',
        'Test "no results" state',
        'Clear search and verify reset',
      ],
      hints: [
        'Use page.getByPlaceholder() to find search input',
        'Type slowly with { delay: 100 }',
        'Wait for results with page.waitForSelector()',
        'Test with various search terms',
      ],
      componentPath: './beginner/SearchBar',
      apiEndpoints: ['/api/items'],
      estimatedTime: 15,
      order: 5,
    },
    {
      id: 'beginner-06-pagination',
      title: 'Pagination',
      description: 'Test pagination controls and page navigation',
      level: 'beginner',
      category: 'Navigation',
      objectives: [
        'Navigate to next/previous pages',
        'Click specific page numbers',
        'Verify current page is highlighted',
        'Test first/last page buttons',
        'Change page size',
      ],
      hints: [
        'Use page.getByRole("button", { name: "Next" })',
        'Assert .toBeDisabled() on first/last pages',
        'Verify URL parameters change',
        'Count visible items per page',
      ],
      componentPath: './beginner/Pagination',
      apiEndpoints: ['/api/items'],
      estimatedTime: 20,
      order: 6,
    },
    {
      id: 'beginner-07-modal-dialog',
      title: 'Modal Dialog',
      description: 'Test opening, closing, and interacting with modal dialogs',
      level: 'beginner',
      category: 'UI Components',
      objectives: [
        'Open modal by clicking trigger button',
        'Verify modal is visible',
        'Close modal with X button',
        'Close modal with overlay click',
        'Submit form inside modal',
      ],
      hints: [
        'Use page.getByRole("dialog") to find modals',
        'Assert visibility with .toBeVisible()',
        'Click outside with page.locator(".overlay").click()',
        'Verify modal disappears after closing',
      ],
      componentPath: './beginner/ModalDialog',
      estimatedTime: 20,
      order: 7,
    },
    {
      id: 'beginner-08-tabs-component',
      title: 'Tabs Component',
      description: 'Test tab switching and content visibility',
      level: 'beginner',
      category: 'UI Components',
      objectives: [
        'Click on different tabs',
        'Verify active tab styling',
        'Verify correct content is displayed',
        'Test keyboard navigation (arrow keys)',
        'Verify URL updates with tab selection',
      ],
      hints: [
        'Use page.getByRole("tab")',
        'Assert aria-selected attribute',
        'Use .press("ArrowRight") for keyboard nav',
        'Check URL hash with page.url()',
      ],
      componentPath: './beginner/TabsComponent',
      estimatedTime: 20,
      order: 8,
    },
    {
      id: 'beginner-09-accordion',
      title: 'Accordion',
      description: 'Test expandable/collapsible accordion sections',
      level: 'beginner',
      category: 'UI Components',
      objectives: [
        'Expand accordion sections',
        'Collapse accordion sections',
        'Test single vs multiple open mode',
        'Verify content visibility',
        'Test nested accordions',
      ],
      hints: [
        'Use page.getByRole("button", { expanded: false })',
        'Assert aria-expanded attribute',
        'Use .toBeHidden() and .toBeVisible()',
        'Test all sections one by one',
      ],
      componentPath: './beginner/Accordion',
      estimatedTime: 15,
      order: 9,
    },
    {
      id: 'beginner-10-tooltip',
      title: 'Tooltip',
      description: 'Test hover tooltips and accessibility',
      level: 'beginner',
      category: 'UI Components',
      objectives: [
        'Hover over elements to show tooltips',
        'Verify tooltip content',
        'Test tooltip positioning',
        'Test tooltip hiding on mouse out',
        'Verify keyboard accessibility',
      ],
      hints: [
        'Use .hover() to trigger tooltips',
        'Use page.getByRole("tooltip")',
        'Wait for tooltip with waitForSelector()',
        'Test focus for keyboard users',
      ],
      componentPath: './beginner/Tooltip',
      estimatedTime: 15,
      order: 10,
    },
    {
      id: 'beginner-11-registration-form',
      title: 'Registration Form',
      description: 'Test user registration with password confirmation and terms acceptance',
      level: 'beginner',
      category: 'Forms',
      objectives: [
        'Fill registration form fields',
        'Test password confirmation matching',
        'Verify password strength indicator',
        'Test terms and conditions checkbox',
        'Verify successful registration',
      ],
      hints: [
        'Use page.getByLabel() for form inputs',
        'Compare password and confirm password values',
        'Assert checkbox with .toBeChecked()',
        'Wait for success message or redirect',
      ],
      componentPath: './beginner/RegistrationForm',
      apiEndpoints: ['/api/auth/register'],
      estimatedTime: 20,
      order: 11,
    },
    {
      id: 'beginner-12-notification-toast',
      title: 'Notification Toast',
      description: 'Test toast notifications with auto-dismiss and multiple types',
      level: 'beginner',
      category: 'UI Components',
      objectives: [
        'Trigger different toast types (success, error, info, warning)',
        'Verify toast content and styling',
        'Test auto-dismiss after timeout',
        'Test manual dismiss with close button',
        'Verify multiple toasts queue correctly',
      ],
      hints: [
        'Use page.getByRole("alert") or data-testid',
        'Wait for toast to disappear with waitForSelector({ state: "hidden" })',
        'Test timing with page.waitForTimeout()',
        'Count visible toasts with .count()',
      ],
      componentPath: './beginner/NotificationToast',
      estimatedTime: 15,
      order: 12,
    },
    {
      id: 'beginner-13-breadcrumb-navigation',
      title: 'Breadcrumb Navigation',
      description: 'Test hierarchical breadcrumb navigation',
      level: 'beginner',
      category: 'Navigation',
      objectives: [
        'Verify breadcrumb trail is displayed',
        'Click breadcrumb links to navigate',
        'Verify current page is highlighted',
        'Test breadcrumb updates on navigation',
        'Verify separator elements',
      ],
      hints: [
        'Use page.getByRole("navigation") with aria-label="breadcrumb"',
        'Use page.getByRole("link") for breadcrumb items',
        'Assert aria-current="page" for current item',
        'Verify URL updates after clicks',
      ],
      componentPath: './beginner/BreadcrumbNavigation',
      estimatedTime: 15,
      order: 13,
    },
    {
      id: 'beginner-14-loading-states',
      title: 'Loading States',
      description: 'Test various loading indicators and skeleton screens',
      level: 'beginner',
      category: 'UI Components',
      objectives: [
        'Verify loading spinner appears during data fetch',
        'Test skeleton screen rendering',
        'Verify loading state disappears when data loads',
        'Test progress indicators',
        'Verify error state after failed load',
      ],
      hints: [
        'Use page.getByRole("status") or aria-busy attribute',
        'Wait for loading to disappear with waitForSelector({ state: "hidden" })',
        'Test with network delay simulation',
        'Assert skeleton elements before content loads',
      ],
      componentPath: './beginner/LoadingStates',
      estimatedTime: 15,
      order: 14,
    },
    {
      id: 'beginner-15-cookie-banner',
      title: 'Cookie Banner',
      description: 'Test GDPR cookie consent banner',
      level: 'beginner',
      category: 'Compliance',
      objectives: [
        'Verify cookie banner appears on first visit',
        'Test accept all cookies',
        'Test reject all cookies',
        'Test customize cookie preferences',
        'Verify banner persistence after choice',
      ],
      hints: [
        'Use page.getByRole("dialog") or data-testid for banner',
        'Check localStorage after cookie choice',
        'Test banner does not appear after consent',
        'Use context.clearCookies() to reset',
      ],
      componentPath: './beginner/CookieBanner',
      estimatedTime: 15,
      order: 15,
    },
    {
      id: 'beginner-16-api-get-requests',
      title: 'API GET Requests',
      description: 'Test basic API GET requests and response validation',
      level: 'beginner',
      category: 'API Testing',
      objectives: [
        'Send GET request to fetch items',
        'Verify response status code (200)',
        'Validate response JSON structure',
        'Test query parameters (limit, offset)',
        'Verify response data matches UI',
      ],
      hints: [
        'Use page.request.get() for API calls',
        'Assert response.status() === 200',
        'Parse JSON with response.json()',
        'Compare API data with page.locator().textContent()',
      ],
      componentPath: './beginner/ApiGetRequests',
      apiEndpoints: ['/api/items'],
      estimatedTime: 15,
      order: 16,
    },
    {
      id: 'beginner-17-api-post-requests',
      title: 'API POST Requests',
      description: 'Test API POST requests for creating resources',
      level: 'beginner',
      category: 'API Testing',
      objectives: [
        'Send POST request with JSON body',
        'Verify 201 Created status code',
        'Validate response contains created resource',
        'Test error handling for invalid data',
        'Verify resource appears in UI',
      ],
      hints: [
        'Use page.request.post() with data parameter',
        'Set Content-Type: application/json header',
        'Assert response status and location header',
        'Test with missing required fields',
      ],
      componentPath: './beginner/ApiPostRequests',
      apiEndpoints: ['/api/items'],
      estimatedTime: 20,
      order: 17,
    },
    {
      id: 'beginner-18-responsive-layout',
      title: 'Responsive Layout',
      description: 'Test responsive design across different viewport sizes',
      level: 'beginner',
      category: 'Mobile',
      objectives: [
        'Test desktop viewport (1920x1080)',
        'Test tablet viewport (768x1024)',
        'Test mobile viewport (375x667)',
        'Verify layout changes at breakpoints',
        'Test elements visibility across viewports',
      ],
      hints: [
        'Use page.setViewportSize({ width: 375, height: 667 })',
        'Assert element visibility with .toBeVisible()',
        'Test CSS grid/flexbox behavior',
        'Verify responsive images and text scaling',
      ],
      componentPath: './beginner/ResponsiveLayout',
      estimatedTime: 20,
      order: 18,
    },
    {
      id: 'beginner-19-mobile-navigation',
      title: 'Mobile Navigation',
      description: 'Test mobile hamburger menu and navigation drawer',
      level: 'beginner',
      category: 'Mobile',
      objectives: [
        'Open hamburger menu on mobile viewport',
        'Navigate through menu items',
        'Close menu with overlay click',
        'Test menu animations',
        'Verify desktop menu vs mobile menu',
      ],
      hints: [
        'Set mobile viewport first',
        'Use page.getByRole("button", { name: /menu/i })',
        'Test menu drawer with slide-in animation',
        'Assert aria-expanded attribute',
      ],
      componentPath: './beginner/MobileNavigation',
      estimatedTime: 20,
      order: 19,
    },
    {
      id: 'beginner-20-touch-gestures',
      title: 'Touch Gestures',
      description: 'Test basic touch interactions: tap, long press, double tap',
      level: 'beginner',
      category: 'Mobile',
      objectives: [
        'Test tap interaction',
        'Test long press (touch and hold)',
        'Test double tap',
        'Verify touch feedback',
        'Test touch target size (44x44px minimum)',
      ],
      hints: [
        'Use page.tap() for touch events',
        'Simulate long press with touchstart/touchend',
        'Test with mobile viewport',
        'Verify visual feedback on touch',
      ],
      componentPath: './beginner/TouchGestures',
      estimatedTime: 20,
      order: 20,
    },
  ],
  intermediate: [
    {
      id: 'intermediate-01-multi-step-form',
      title: 'Multi-Step Form',
      description: 'Test a wizard-style form with multiple steps and validation',
      level: 'intermediate',
      category: 'Forms',
      objectives: [
        'Navigate through form steps',
        'Validate each step before proceeding',
        'Test back button functionality',
        'Verify progress indicator',
        'Submit complete form',
      ],
      hints: [
        'Track current step with data attributes',
        'Test validation on "Next" click',
        'Verify previous data is retained',
        'Use .nth() for step indicators',
      ],
      componentPath: './intermediate/MultiStepForm',
      estimatedTime: 30,
      order: 11,
    },
    {
      id: 'intermediate-02-file-upload',
      title: 'File Upload',
      description: 'Test file upload with drag-and-drop and progress tracking',
      level: 'intermediate',
      category: 'File Handling',
      objectives: [
        'Upload files via input',
        'Test drag-and-drop upload',
        'Verify upload progress',
        'Test file type validation',
        'Remove uploaded files',
      ],
      hints: [
        'Use page.setInputFiles() for uploads',
        'Test drag events with dispatchEvent',
        'Wait for progress bars to complete',
        'Verify file size limits',
      ],
      componentPath: './intermediate/FileUpload',
      apiEndpoints: ['/api/files/upload'],
      estimatedTime: 25,
      order: 12,
    },
    {
      id: 'intermediate-03-realtime-chat',
      title: 'Real-Time Chat',
      description: 'Test WebSocket chat with multiple users and rooms',
      level: 'intermediate',
      category: 'WebSocket',
      objectives: [
        'Connect to chat room',
        'Send messages',
        'Receive messages in real-time',
        'Test multiple browser contexts',
        'Verify message timestamps',
      ],
      hints: [
        'Use multiple browser contexts for multi-user testing',
        'Wait for WebSocket connections',
        'Assert message order and content',
        'Test disconnect/reconnect scenarios',
      ],
      componentPath: './intermediate/RealtimeChat',
      apiEndpoints: ['/api/ws/chat'],
      estimatedTime: 35,
      order: 13,
    },
    // Placeholders for remaining intermediate challenges
    {
      id: 'intermediate-04-drag-drop',
      title: 'Drag and Drop',
      description: 'Test drag-and-drop interactions for reordering items',
      level: 'intermediate',
      category: 'Interactions',
      objectives: ['Drag items', 'Drop in new positions', 'Verify order updates'],
      hints: ['Use page.dragAndDrop()', 'Verify data-index attributes'],
      componentPath: './intermediate/DragDrop',
      estimatedTime: 25,
      order: 14,
    },
    {
      id: 'intermediate-05-infinite-scroll',
      title: 'Infinite Scroll',
      description: 'Test infinite scroll pagination',
      level: 'intermediate',
      category: 'Lists',
      objectives: ['Scroll to trigger load', 'Verify new items appear', 'Test scroll to top'],
      hints: ['Use page.evaluate() to scroll', 'Wait for loading indicators'],
      componentPath: './intermediate/InfiniteScroll',
      estimatedTime: 20,
      order: 15,
    },
    {
      id: 'intermediate-06-autocomplete',
      title: 'Autocomplete',
      description: 'Test autocomplete dropdown with keyboard navigation',
      level: 'intermediate',
      category: 'Input',
      objectives: ['Type to show suggestions', 'Navigate with arrow keys', 'Select suggestion'],
      hints: ['Use .press("ArrowDown")', 'Assert role="option"'],
      componentPath: './intermediate/Autocomplete',
      estimatedTime: 20,
      order: 16,
    },
    {
      id: 'intermediate-07-date-picker',
      title: 'Date Picker',
      description: 'Test calendar date picker component',
      level: 'intermediate',
      category: 'Input',
      objectives: ['Open calendar', 'Select date', 'Navigate months', 'Verify input value'],
      hints: ['Use page.getByRole("gridcell")', 'Test date formatting'],
      componentPath: './intermediate/DatePicker',
      estimatedTime: 25,
      order: 17,
    },
    {
      id: 'intermediate-08-rich-text-editor',
      title: 'Rich Text Editor',
      description: 'Test WYSIWYG editor with formatting',
      level: 'intermediate',
      category: 'Input',
      objectives: ['Type text', 'Apply formatting', 'Insert links', 'Verify HTML output'],
      hints: ['Use contenteditable elements', 'Test toolbar buttons'],
      componentPath: './intermediate/RichTextEditor',
      estimatedTime: 30,
      order: 18,
    },
    {
      id: 'intermediate-09-image-gallery',
      title: 'Image Gallery',
      description: 'Test image gallery with lightbox and navigation',
      level: 'intermediate',
      category: 'Media',
      objectives: ['Open images', 'Navigate gallery', 'Close lightbox', 'Test thumbnails'],
      hints: ['Test keyboard shortcuts', 'Verify image loading'],
      componentPath: './intermediate/ImageGallery',
      estimatedTime: 25,
      order: 19,
    },
    {
      id: 'intermediate-10-data-table',
      title: 'Data Table',
      description: 'Test sortable, filterable data table',
      level: 'intermediate',
      category: 'Lists',
      objectives: ['Sort columns', 'Filter rows', 'Select rows', 'Export data'],
      hints: ['Test column headers', 'Verify sort indicators'],
      componentPath: './intermediate/DataTable',
      estimatedTime: 30,
      order: 20,
    },
    {
      id: 'intermediate-11-color-picker',
      title: 'Color Picker',
      description: 'Test color picker component with hex, RGB, and preset colors',
      level: 'intermediate',
      category: 'Input',
      objectives: [
        'Open color picker',
        'Select color from palette',
        'Enter hex color code',
        'Use RGB sliders',
        'Select from preset colors',
      ],
      hints: [
        'Use page.locator(\'input[type="color"]\') for native picker',
        'Test custom color picker interactions',
        'Verify color value updates in different formats',
        'Test color preview updates',
      ],
      componentPath: './intermediate/ColorPicker',
      estimatedTime: 25,
      order: 21,
    },
    {
      id: 'intermediate-12-slider-range',
      title: 'Slider / Range Input',
      description: 'Test slider and dual-handle range inputs',
      level: 'intermediate',
      category: 'Input',
      objectives: [
        'Drag single slider handle',
        'Test dual-handle range slider',
        'Verify min/max constraints',
        'Test step increments',
        'Verify value display updates',
      ],
      hints: [
        'Use page.locator(\'input[type="range"]\') for native sliders',
        'Use .fill() with value or dragTo for custom sliders',
        'Assert slider value with .inputValue()',
        'Test keyboard arrow keys for increments',
      ],
      componentPath: './intermediate/SliderRange',
      estimatedTime: 20,
      order: 22,
    },
    {
      id: 'intermediate-13-form-validation',
      title: 'Form Validation Library',
      description: 'Test comprehensive form validation with real-time feedback',
      level: 'intermediate',
      category: 'Forms',
      objectives: [
        'Test field-level validation on blur',
        'Test async validation (unique email)',
        'Verify multiple validation rules',
        'Test form-level validation on submit',
        'Verify error message aggregation',
      ],
      hints: [
        'Trigger blur events with .blur()',
        'Wait for async validation with waitForSelector',
        'Test required, email, minLength, pattern rules',
        'Verify error messages appear and disappear',
      ],
      componentPath: './intermediate/FormValidation',
      estimatedTime: 30,
      order: 23,
    },
    {
      id: 'intermediate-14-virtual-scroll',
      title: 'Virtual Scrolling List',
      description: 'Test virtual scrolling with large datasets',
      level: 'intermediate',
      category: 'Performance',
      objectives: [
        'Load large dataset (1000+ items)',
        'Verify only visible items are rendered',
        'Scroll through list',
        'Verify DOM recycling',
        'Test scroll performance',
      ],
      hints: [
        'Count rendered DOM elements with .count()',
        'Use page.evaluate() to scroll to specific positions',
        'Verify items update as you scroll',
        'Test scroll to specific item by index',
      ],
      componentPath: './intermediate/VirtualScroll',
      estimatedTime: 30,
      order: 24,
    },
    {
      id: 'intermediate-15-lazy-loading',
      title: 'Lazy Loading Images',
      description: 'Test image lazy loading with Intersection Observer',
      level: 'intermediate',
      category: 'Performance',
      objectives: [
        'Verify placeholder images initially',
        'Scroll to trigger image loading',
        'Verify images load on viewport entry',
        'Test loading attribute',
        'Verify error state for broken images',
      ],
      hints: [
        'Assert src attribute changes from placeholder to actual',
        'Use page.evaluate() to scroll images into view',
        'Test loading="lazy" attribute',
        'Verify alt text for accessibility',
      ],
      componentPath: './intermediate/LazyLoading',
      estimatedTime: 25,
      order: 25,
    },
    {
      id: 'intermediate-16-keyboard-shortcuts',
      title: 'Keyboard Shortcuts',
      description: 'Test global and contextual keyboard shortcuts',
      level: 'intermediate',
      category: 'Accessibility',
      objectives: [
        'Test global shortcuts (Ctrl+K for search)',
        'Test context-specific shortcuts',
        'Open keyboard shortcuts help dialog',
        'Verify shortcuts work across different contexts',
        'Test shortcut conflict prevention',
      ],
      hints: [
        'Use page.keyboard.press("Control+K")',
        'Test Meta key for Mac: "Meta+K"',
        'Verify focus changes after shortcuts',
        'Test Escape key to close dialogs',
      ],
      componentPath: './intermediate/KeyboardShortcuts',
      estimatedTime: 25,
      order: 26,
    },
    {
      id: 'intermediate-17-context-menu',
      title: 'Context Menu',
      description: 'Test right-click context menus',
      level: 'intermediate',
      category: 'Interactions',
      objectives: [
        'Right-click to open context menu',
        'Select menu items',
        'Test nested submenus',
        'Test keyboard navigation in menu',
        'Verify menu closes on click outside',
      ],
      hints: [
        'Use page.click({ button: "right" }) for right-click',
        'Use page.getByRole("menu") and role="menuitem"',
        'Test arrow keys for menu navigation',
        'Verify menu position relative to click',
      ],
      componentPath: './intermediate/ContextMenu',
      estimatedTime: 25,
      order: 27,
    },
    {
      id: 'intermediate-18-clipboard',
      title: 'Clipboard Operations',
      description: 'Test copy, cut, and paste functionality',
      level: 'intermediate',
      category: 'Browser APIs',
      objectives: [
        'Copy text to clipboard',
        'Paste from clipboard',
        'Test copy button',
        'Verify clipboard permissions',
        'Test clipboard with keyboard shortcuts',
      ],
      hints: [
        'Use navigator.clipboard.writeText() in page context',
        'Read clipboard with page.evaluate()',
        'Test Ctrl+C / Ctrl+V keyboard shortcuts',
        'Handle clipboard permissions in headless mode',
      ],
      componentPath: './intermediate/Clipboard',
      estimatedTime: 20,
      order: 28,
    },
    {
      id: 'intermediate-19-api-crud-operations',
      title: 'API CRUD Operations',
      description: 'Test complete Create, Read, Update, Delete API operations',
      level: 'intermediate',
      category: 'API Testing',
      objectives: [
        'Create resource with POST',
        'Read resource with GET',
        'Update resource with PUT/PATCH',
        'Delete resource with DELETE',
        'Verify status codes (200, 201, 204, 404)',
      ],
      hints: [
        'Use page.request.post/get/put/delete()',
        'Store created resource ID for subsequent operations',
        'Assert 404 after deletion',
        'Test partial updates with PATCH vs full with PUT',
      ],
      componentPath: './intermediate/ApiCrudOperations',
      apiEndpoints: ['/api/items', '/api/items/:id'],
      estimatedTime: 30,
      order: 29,
    },
    {
      id: 'intermediate-20-api-authentication',
      title: 'API Authentication',
      description: 'Test API authentication with tokens and protected endpoints',
      level: 'intermediate',
      category: 'API Testing',
      objectives: [
        'Login and obtain JWT token',
        'Send authenticated requests with Bearer token',
        'Test 401 Unauthorized without token',
        'Test 403 Forbidden with invalid token',
        'Test token expiration and refresh',
      ],
      hints: [
        'Store token from login response',
        'Add Authorization header: Bearer <token>',
        'Test protected endpoints without auth',
        'Use page.request.storageState() to persist auth',
      ],
      componentPath: './intermediate/ApiAuthentication',
      apiEndpoints: ['/api/auth/login', '/api/users/me'],
      estimatedTime: 30,
      order: 30,
    },
    {
      id: 'intermediate-21-swipe-cards',
      title: 'Swipe Cards',
      description: 'Test swipeable card interface (Tinder-style)',
      level: 'intermediate',
      category: 'Mobile',
      objectives: [
        'Swipe card left to reject',
        'Swipe card right to accept',
        'Test swipe threshold',
        'Verify card stack behavior',
        'Test undo last swipe',
      ],
      hints: [
        'Use page.mouse.move() to simulate swipe',
        'Test swipe distance and velocity',
        'Verify card removal animation',
        'Test on mobile viewport',
      ],
      componentPath: './intermediate/SwipeCards',
      estimatedTime: 30,
      order: 31,
    },
    {
      id: 'intermediate-22-mobile-form-inputs',
      title: 'Mobile Form Inputs',
      description: 'Test mobile-specific input types and keyboard behavior',
      level: 'intermediate',
      category: 'Mobile',
      objectives: [
        'Test tel input with numeric keyboard',
        'Test email input with @ keyboard',
        'Test number input with numeric keyboard',
        'Test date/time pickers on mobile',
        'Verify input zoom prevention',
      ],
      hints: [
        'Set mobile viewport',
        'Use input type="tel", type="email", etc.',
        'Test inputmode attribute',
        'Verify font-size >= 16px to prevent zoom',
      ],
      componentPath: './intermediate/MobileFormInputs',
      estimatedTime: 25,
      order: 32,
    },
    {
      id: 'intermediate-23-pull-to-refresh',
      title: 'Pull to Refresh',
      description: 'Test pull-to-refresh interaction on mobile',
      level: 'intermediate',
      category: 'Mobile',
      objectives: [
        'Pull down at top of page',
        'Verify refresh indicator appears',
        'Test content reload on release',
        'Verify refresh animation',
        'Test overscroll behavior',
      ],
      hints: [
        'Use page.mouse.move() to simulate pull gesture',
        'Start from top of scrollable container',
        'Verify loading state during refresh',
        'Test on mobile viewport',
      ],
      componentPath: './intermediate/PullToRefresh',
      estimatedTime: 25,
      order: 33,
    },
  ],
  senior: [
    {
      id: 'senior-1-api-rate-limiting',
      title: 'API Rate Limiting',
      description: 'Test API rate limiting and throttling behavior',
      level: 'senior',
      category: 'API Testing',
      objectives: [
        'Send multiple rapid requests',
        'Verify 429 Too Many Requests status',
        'Test rate limit headers (X-RateLimit-*)',
        'Test retry-after header',
        'Verify rate limit reset',
      ],
      hints: [
        'Use Promise.all() for concurrent requests',
        'Assert response headers for rate limit info',
        'Test with different rate limits per endpoint',
        'Implement exponential backoff retry logic',
      ],
      componentPath: './senior/ApiRateLimiting',
      apiEndpoints: ['/api/items'],
      estimatedTime: 35,
      order: 1,
    },
    {
      id: 'senior-2-api-schema-validation',
      title: 'API Schema Validation',
      description: 'Test API response schema validation with JSON Schema',
      level: 'senior',
      category: 'API Testing',
      objectives: [
        'Define JSON schema for API response',
        'Validate response against schema',
        'Test required vs optional fields',
        'Test field types and formats',
        'Test array and nested object validation',
      ],
      hints: [
        'Use JSON Schema validator library',
        'Test with valid and invalid responses',
        'Assert specific error messages for violations',
        'Test edge cases (null, empty arrays, etc.)',
      ],
      componentPath: './senior/ApiSchemaValidation',
      apiEndpoints: ['/api/items', '/api/users'],
      estimatedTime: 40,
      order: 2,
    },
    {
      id: 'senior-3-admin-dashboard',
      title: 'Admin Dashboard',
      description: 'Test complex dashboard with charts, filters, and real-time updates',
      level: 'senior',
      category: 'Dashboard',
      objectives: [
        'Load dashboard data',
        'Apply date range filters',
        'Interact with charts',
        'Test real-time data updates',
        'Export reports',
      ],
      hints: [
        'Use canvas for chart interactions',
        'Test multiple data sources',
        'Verify calculations',
        'Test refresh mechanisms',
      ],
      componentPath: './senior/AdminDashboard',
      apiEndpoints: ['/api/items', '/api/users', '/api/orders'],
      estimatedTime: 45,
      order: 3,
    },
    // Placeholders for remaining senior challenges
    {
      id: 'senior-4-admin-panel',
      title: 'Admin Panel CRUD',
      description: 'Test complete admin panel with user management',
      level: 'senior',
      category: 'CRUD',
      objectives: ['Create users', 'Edit users', 'Delete users', 'Test permissions'],
      hints: ['Test role-based access', 'Verify audit logs'],
      componentPath: './senior/AdminPanel',
      estimatedTime: 40,
      order: 4,
    },
    {
      id: 'senior-5-ecommerce-checkout',
      title: 'E-commerce Checkout',
      description: 'Test complete checkout flow with payment simulation',
      level: 'senior',
      category: 'E-commerce',
      objectives: ['Add to cart', 'Enter shipping', 'Select payment', 'Complete order'],
      hints: ['Test validation at each step', 'Verify order confirmation'],
      componentPath: './senior/EcommerceCheckout',
      estimatedTime: 50,
      order: 5,
    },
    {
      id: 'senior-04-social-feed',
      title: 'Social Media Feed',
      description: 'Test infinite social feed with likes, comments, shares',
      level: 'senior',
      category: 'Social',
      objectives: ['Load posts', 'Like/unlike', 'Add comments', 'Share posts'],
      hints: ['Test optimistic updates', 'Verify real-time counts'],
      componentPath: './senior/SocialFeed',
      estimatedTime: 40,
      order: 24,
    },
    {
      id: 'senior-05-analytics-charts',
      title: 'Analytics Charts',
      description: 'Test interactive analytics with multiple chart types',
      level: 'senior',
      category: 'Visualization',
      objectives: ['Switch chart types', 'Filter data', 'Hover tooltips', 'Export charts'],
      hints: ['Test SVG/Canvas elements', 'Verify data accuracy'],
      componentPath: './senior/AnalyticsCharts',
      estimatedTime: 35,
      order: 25,
    },
    {
      id: 'senior-06-kanban-board',
      title: 'Kanban Board',
      description: 'Test kanban board with drag-and-drop and status updates',
      level: 'senior',
      category: 'Project Management',
      objectives: ['Drag cards', 'Change status', 'Edit cards', 'Filter by assignee'],
      hints: ['Test column limits', 'Verify persistence'],
      componentPath: './senior/KanbanBoard',
      estimatedTime: 45,
      order: 26,
    },
    {
      id: 'senior-07-video-player',
      title: 'Video Player',
      description: 'Test custom video player controls',
      level: 'senior',
      category: 'Media',
      objectives: ['Play/pause', 'Seek', 'Volume control', 'Fullscreen', 'Playback speed'],
      hints: ['Test video element', 'Verify time updates'],
      componentPath: './senior/VideoPlayer',
      estimatedTime: 30,
      order: 27,
    },
    {
      id: 'senior-08-map-integration',
      title: 'Map Integration',
      description: 'Test interactive map with markers and routes',
      level: 'senior',
      category: 'Maps',
      objectives: ['Load map', 'Add markers', 'Draw routes', 'Search locations'],
      hints: ['Test map library integration', 'Verify coordinates'],
      componentPath: './senior/MapIntegration',
      estimatedTime: 40,
      order: 28,
    },
    {
      id: 'senior-09-feature-flags',
      title: 'Feature Flags',
      description: 'Test A/B testing with feature flag toggling',
      level: 'senior',
      category: 'Configuration',
      objectives: ['Toggle features', 'Test variants', 'Verify UI changes', 'Test persistence'],
      hints: ['Test different user segments', 'Verify analytics'],
      componentPath: './senior/FeatureFlags',
      apiEndpoints: ['/api/flags'],
      estimatedTime: 35,
      order: 29,
    },
    {
      id: 'senior-10-multi-tab-sync',
      title: 'Multi-Tab Sync',
      description: 'Test session synchronization across multiple tabs',
      level: 'senior',
      category: 'Advanced',
      objectives: [
        'Open multiple tabs',
        'Sync state',
        'Test logout propagation',
        'Verify conflicts',
      ],
      hints: ['Use multiple browser contexts', 'Test localStorage events'],
      componentPath: './senior/MultiTabSync',
      estimatedTime: 45,
      order: 30,
    },
    {
      id: 'senior-11-multi-language',
      title: 'Multi-Language (i18n)',
      description: 'Test internationalization and localization',
      level: 'senior',
      category: 'Internationalization',
      objectives: [
        'Switch between languages',
        'Verify translations load correctly',
        'Test RTL layout for Arabic/Hebrew',
        'Test number and date formatting',
        'Verify language persistence',
      ],
      hints: [
        'Use language selector dropdown',
        'Assert text content changes after language switch',
        'Test dir="rtl" attribute for RTL languages',
        'Verify localStorage saves language preference',
      ],
      componentPath: './senior/MultiLanguage',
      estimatedTime: 40,
      order: 31,
    },
    {
      id: 'senior-12-theme-switcher',
      title: 'Theme Switcher',
      description: 'Test theme switching with light, dark, and custom themes',
      level: 'senior',
      category: 'Theming',
      objectives: [
        'Switch between light and dark themes',
        'Create custom theme with color picker',
        'Test system preference detection',
        'Verify theme persistence',
        'Test CSS variable updates',
      ],
      hints: [
        'Use theme selector buttons',
        'Assert data-theme or class attributes on html/body',
        'Test prefers-color-scheme media query',
        'Verify localStorage saves theme preference',
      ],
      componentPath: './senior/ThemeSwitcher',
      estimatedTime: 35,
      order: 32,
    },
    {
      id: 'senior-13-code-editor',
      title: 'Code Editor',
      description: 'Test code editor with syntax highlighting and autocomplete',
      level: 'senior',
      category: 'Advanced Input',
      objectives: [
        'Type code in editor',
        'Verify syntax highlighting',
        'Test line numbers',
        'Test code folding',
        'Test autocomplete suggestions',
      ],
      hints: [
        'Locate editor with .monaco-editor or .CodeMirror',
        'Use page.locator(".view-line") for code lines',
        'Test keyboard shortcuts (Ctrl+Space for autocomplete)',
        'Verify syntax tokens with CSS classes',
      ],
      componentPath: './senior/CodeEditor',
      estimatedTime: 45,
      order: 33,
    },
    {
      id: 'senior-14-calendar-scheduler',
      title: 'Calendar / Scheduler',
      description: 'Test full calendar with event scheduling',
      level: 'senior',
      category: 'Complex UI',
      objectives: [
        'Switch calendar views (day/week/month)',
        'Create new events',
        'Edit existing events',
        'Drag to resize events',
        'Test recurring events',
      ],
      hints: [
        'Use view switcher buttons',
        'Click on calendar cells to create events',
        'Use dragAndDrop for event resize',
        'Test event conflict detection',
      ],
      componentPath: './senior/CalendarScheduler',
      estimatedTime: 50,
      order: 34,
    },
    {
      id: 'senior-15-offline-mode',
      title: 'Offline Mode / PWA',
      description: 'Test Progressive Web App offline functionality',
      level: 'senior',
      category: 'PWA',
      objectives: [
        'Test offline detection',
        'Verify cached content works offline',
        'Test background sync when online',
        'Test service worker registration',
        'Test install prompt',
      ],
      hints: [
        'Use context.setOffline(true) to simulate offline',
        'Verify offline indicator appears',
        'Test cached API responses',
        'Use page.evaluate() to check service worker',
      ],
      componentPath: './senior/OfflineMode',
      estimatedTime: 45,
      order: 35,
    },
    {
      id: 'senior-16-oauth-flows',
      title: 'OAuth / SSO Authentication',
      description: 'Test OAuth login flows and single sign-on',
      level: 'senior',
      category: 'Security',
      objectives: [
        'Test OAuth provider redirect',
        'Handle popup-based OAuth',
        'Test redirect-based OAuth',
        'Verify token exchange',
        'Test multi-factor authentication',
      ],
      hints: [
        'Use context.waitForEvent("page") for popups',
        'Handle OAuth redirects with waitForURL',
        'Test different providers (Google, GitHub, etc.)',
        'Verify access token storage',
      ],
      componentPath: './senior/OAuthFlows',
      apiEndpoints: ['/api/auth/oauth'],
      estimatedTime: 50,
      order: 36,
    },
    {
      id: 'senior-17-performance-monitoring',
      title: 'Performance Monitoring',
      description: 'Test performance metrics and Web Vitals dashboard',
      level: 'senior',
      category: 'Performance',
      objectives: [
        'Capture Core Web Vitals (LCP, FID, CLS)',
        'Test Performance API metrics',
        'Visualize resource timing waterfall',
        'Monitor network requests',
        'Test performance budgets',
      ],
      hints: [
        'Use page.evaluate() to access performance APIs',
        'Test web-vitals library integration',
        'Verify metric thresholds (good/needs improvement/poor)',
        'Assert performance marks and measures',
      ],
      componentPath: './senior/PerformanceMonitoring',
      estimatedTime: 45,
      order: 37,
    },
    {
      id: 'senior-18-orientation-changes',
      title: 'Orientation Changes',
      description: 'Test device orientation changes and adaptive layouts',
      level: 'senior',
      category: 'Mobile',
      objectives: [
        'Test portrait orientation',
        'Test landscape orientation',
        'Verify layout adaptation on orientation change',
        'Test orientation lock',
        'Verify media query behavior',
      ],
      hints: [
        'Use page.setViewportSize() with rotated dimensions',
        'Test with tablet viewport (768x1024 vs 1024x768)',
        'Verify CSS media queries (orientation: portrait/landscape)',
        'Test orientation change events',
      ],
      componentPath: './senior/OrientationChanges',
      estimatedTime: 35,
      order: 38,
    },
  ],
};

export function getAllChallenges() {
  return [
    ...challengeRegistry.beginner,
    ...challengeRegistry.intermediate,
    ...challengeRegistry.senior,
  ];
}

export function getChallengeById(id: string) {
  return getAllChallenges().find((c) => c.id === id);
}

export function getChallengesByLevel(level: ChallengeLevel) {
  return challengeRegistry[level];
}
